remote_theme: just-the-docs/just-the-docs
theme: "just-the-docs"

title: Rewls
description: Blog for study log
baseurl: "/blog"
url: "https://rewls.github.io"

# Enable or disable the site search
# Sipports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Aux links for the upper right navigation
aux_links:
  "Github":
    - "//github.com/rewls"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/rewls/rewls.github.io" # the github URL for your repo

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil
